### ISSUE TITLE
End game doesn't always work.

### ISSUE THREAD

**Issue by Ivan-Johnson** [Einhaender/ERS#21]
failure log:
`2016-06-07T12:33:17.305-05:00 (FINER)   [Game] [tryFlip]                :AI 1 flipped the Queen of clubs
2016-06-07T12:33:17.478-05:00 (FINER)   [Game] [tryFlip]                :AI 2 flipped the 5 of spades
2016-06-07T12:33:17.479-05:00 (FINE)    [Game] [tryFlip]                :AI 2 is eliminated because they flipped their last card
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
    at com.silentsalamander.runner.CardStack.removeTopCard(CardStack.java:105)
    at com.silentsalamander.runner.Game.tryFlip(Game.java:202)
    at com.silentsalamander.runner.AI.actionPerformed(AI.java:161)
    at javax.swing.Timer.fireActionPerformed(Timer.java:313)
    at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

success log:
`2016-06-07T12:33:02.724-05:00 (FINER)   [Game] [tryFlip]                :AI 2 flipped the 3 of diamonds
2016-06-07T12:33:02.894-05:00 (FINER)   [Game] [tryFlip]                :AI 1 flipped the 10 of clubs
2016-06-07T12:33:03.076-05:00 (FINER)   [Game] [tryFlip]                :AI 2 flipped the 2 of spades
2016-06-07T12:33:03.232-05:00 (FINER)   [Game] [tryFlip]                :AI 1 flipped the 5 of diamonds
2016-06-07T12:33:03.386-05:00 (FINER)   [Game] [tryFlip]                :AI 2 flipped the 6 of diamonds
2016-06-07T12:33:03.387-05:00 (FINE)    [Game] [tryFlip]                :AI 2 is eliminated because they flipped their last card`

**Comment by Ivan-Johnson** [comment]
another failure:
`2016-06-07T12:37:55.823-05:00 (FINER)   [Game] [trySlap]                :AI 1 is trying to slap: 10 of diamonds, Jack of clubs, King of clubs, 7 of diamonds, 10 of clubs, 
2016-06-07T12:37:55.824-05:00 (FINE)    [Game] [trySlap]                :AI 1 picked up some cards
2016-06-07T12:37:55.970-05:00 (FINER)   [Game] [tryFlip]                :AI 1 flipped the 2 of spades
2016-06-07T12:37:56.134-05:00 (FINER)   [Game] [tryFlip]                :AI 2 flipped the 6 of clubs
2016-06-07T12:37:56.309-05:00 (FINER)   [Game] [tryFlip]                :AI 3 flipped the Ace of hearts
2016-06-07T12:37:56.447-05:00 (FINER)   [Game] [tryFlip]                :AI 4 flipped the 2 of diamonds
2016-06-07T12:37:56.642-05:00 (FINER)   [Game] [tryFlip]                :AI 4 flipped the 5 of diamonds
2016-06-07T12:37:56.801-05:00 (FINER)   [Game] [tryFlip]                :AI 4 flipped the 10 of hearts
2016-06-07T12:37:56.801-05:00 (FINE)    [Game] [tryFlip]                :AI 4 is eliminated because they flipped their last card`

**Comment by Ivan-Johnson** [comment]
success:
`2016-06-07T12:38:49.256-05:00 (FINER)   [Game] [trySlap]                :AI 1 is trying to slap: 2 of spades, 9 of hearts, 6 of hearts, 5 of diamonds, Ace of hearts, 
2016-06-07T12:38:49.256-05:00 (FINE)    [Game] [trySlap]                :AI 1 picked up some cards
2016-06-07T12:38:49.412-05:00 (FINER)   [Game] [tryFlip]                :AI 1 flipped the Jack of diamonds
2016-06-07T12:38:49.571-05:00 (FINER)   [Game] [tryFlip]                :AI 2 flipped the 2 of clubs
2016-06-07T12:38:49.723-05:00 (FINER)   [Game] [trySlap]                :AI 1 is trying to slap: 2 of clubs, Jack of diamonds, 
2016-06-07T12:38:49.723-05:00 (FINE)    [Game] [trySlap]                :AI 1 picked up some cards
2016-06-07T12:38:49.856-05:00 (FINER)   [Game] [tryFlip]                :AI 1 flipped the 8 of diamonds
2016-06-07T12:38:49.984-05:00 (FINER)   [Game] [tryFlip]                :AI 2 flipped the 9 of diamonds
2016-06-07T12:38:50.120-05:00 (FINER)   [Game] [tryFlip]                :AI 3 flipped the 5 of spades
2016-06-07T12:38:50.250-05:00 (FINER)   [Game] [tryFlip]                :AI 4 flipped the Jack of hearts
2016-06-07T12:38:50.388-05:00 (FINER)   [Game] [tryFlip]                :AI 1 flipped the Queen of diamonds
2016-06-07T12:38:50.547-05:00 (FINER)   [Game] [tryFlip]                :AI 2 flipped the 10 of hearts
2016-06-07T12:38:50.691-05:00 (FINER)   [Game] [tryFlip]                :AI 2 flipped the 4 of clubs
2016-06-07T12:38:50.692-05:00 (FINE)    [Game] [tryFlip]                :AI 2 is eliminated because they flipped their last card
2016-06-07T12:38:50.838-05:00 (FINER)   [Game] [trySlap]                :AI 1 is trying to slap: 4 of clubs, 10 of hearts, Queen of diamonds, Jack of hearts, 5 of spades, 
2016-06-07T12:38:50.839-05:00 (FINE)    [Game] [trySlap]                :AI 1 picked up some cards
2016-06-07T12:38:50.991-05:00 (FINER)   [Game] [tryFlip]                :AI 1 flipped the 3 of hearts`

**Comment by Ivan-Johnson** [comment]
failure:
`2016-06-07T12:40:45.447-05:00 (FINER)   [Game] [tryFlip]                :AI 2 flipped the 4 of hearts
2016-06-07T12:40:45.536-05:00 (FINER)   [Game] [trySlap]                :AI 1 is trying to slap: 4 of hearts, Jack of clubs, 7 of clubs, 9 of diamonds, 10 of diamonds, 
2016-06-07T12:40:45.536-05:00 (FINE)    [Game] [trySlap]                :AI 1 picked up some cards
2016-06-07T12:40:45.628-05:00 (FINER)   [Game] [tryFlip]                :AI 1 flipped the Ace of hearts
2016-06-07T12:40:45.719-05:00 (FINER)   [Game] [tryFlip]                :AI 2 flipped the 4 of spades
2016-06-07T12:40:45.719-05:00 (FINE)    [Game] [tryFlip]                :AI 2 is eliminated because they flipped their last card
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
    at com.silentsalamander.runner.CardStack.removeTopCard(CardStack.java:105)
    at com.silentsalamander.runner.Game.tryFlip(Game.java:202)
    at com.silentsalamander.runner.AI.actionPerformed(AI.java:161)
    at javax.swing.Timer.fireActionPerformed(Timer.java:313)
    at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by Ivan-Johnson** [comment]
success, then failure:
`2016-06-07T12:42:13.570-05:00 (FINER)   [Game] [tryFlip]                :AI 2 flipped the Jack of diamonds
2016-06-07T12:42:13.653-05:00 (FINER)   [Game] [tryFlip]                :AI 3 flipped the 6 of diamonds
2016-06-07T12:42:13.739-05:00 (FINER)   [Game] [trySlap]                :AI 2 is trying to slap: 6 of diamonds, Jack of diamonds, 2 of diamonds, 7 of spades, King of hearts, 
2016-06-07T12:42:13.740-05:00 (FINE)    [Game] [trySlap]                :AI 2 picked up some cards
2016-06-07T12:42:13.827-05:00 (FINER)   [Game] [tryFlip]                :AI 2 flipped the 6 of spades
2016-06-07T12:42:13.912-05:00 (FINER)   [Game] [tryFlip]                :AI 3 flipped the 5 of diamonds
2016-06-07T12:42:13.999-05:00 (FINER)   [Game] [tryFlip]                :AI 4 flipped the 4 of hearts
2016-06-07T12:42:14.088-05:00 (FINER)   [Game] [tryFlip]                :AI 1 flipped the 10 of diamonds
2016-06-07T12:42:14.088-05:00 (FINE)    [Game] [tryFlip]                :AI 1 is eliminated because they flipped their last card
2016-06-07T12:42:14.172-05:00 (FINER)   [Game] [tryFlip]                :AI 2 flipped the 10 of spades
2016-06-07T12:42:14.254-05:00 (FINER)   [Game] [trySlap]                :AI 4 is trying to slap: 10 of spades, 10 of diamonds, 4 of hearts, 5 of diamonds, 6 of spades, 
2016-06-07T12:42:14.255-05:00 (FINE)    [Game] [trySlap]                :AI 4 just slapped some cards!
2016-06-07T12:42:14.337-05:00 (FINER)   [Game] [tryFlip]                :AI 4 flipped the Queen of clubs
2016-06-07T12:42:14.419-05:00 (FINER)   [Game] [tryFlip]                :AI 2 flipped the Ace of clubs
2016-06-07T12:42:14.501-05:00 (FINER)   [Game] [tryFlip]                :AI 3 flipped the 5 of clubs
2016-06-07T12:42:14.502-05:00 (FINE)    [Game] [tryFlip]                :AI 3 is eliminated because they flipped their last card
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
    at com.silentsalamander.runner.CardStack.removeTopCard(CardStack.java:105)
    at com.silentsalamander.runner.Game.tryFlip(Game.java:202)
    at com.silentsalamander.runner.AI.actionPerformed(AI.java:161)
    at javax.swing.Timer.fireActionPerformed(Timer.java:313)
    at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`
